[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "fraud-rule-engine-service"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["app"]
