apiVersion: v1
kind: Secret
metadata:
  name: fraud-app-secret
  namespace: fraud
type: Opaque
stringData:
  SECRET_KEY: "change-me"
  DATABASE_URL: "postgresql+psycopg2://fraud:fraud@fraud-db:5432/fraud_db"
