apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fraud-db
  namespace: fraud
spec:
  serviceName: fraud-db
  replicas: 1
  selector:
    matchLabels:
      app: fraud-db
  template:
    metadata:
      labels:
        app: fraud-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fraud_db
            - name: POSTGRES_USER
              value: fraud
            - name: POSTGRES_PASSWORD
              value: fraud
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
