apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fraud
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: "fraud-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["fraud-api.fraud.svc.cluster.local:80"]
